/**
 * Data Service Layer (Phase 2 Production Ready)
 * Priority 1: Fetches `today.json` generated daily at 08:00 AM by GitHub Actions.
 * Priority 2: Fallback to local `mockData.js` if `today.json` is unavailable.
 */

import { mockData } from '../mockData.js';

let liveDataCache = null;

/**
 * Fetch `today.json` from server root
 */
async function fetchLiveTodayJson() {
  if (liveDataCache) return liveDataCache;
  try {
    const response = await fetch('./today.json?t=' + Date.now());
    if (response.ok) {
      liveDataCache = await response.json();
      console.log("Successfully loaded today.json generated by GitHub Actions!");
      return liveDataCache;
    }
  } catch (e) {
    console.warn("`today.json` not available or running offline, using mockData fallback:", e);
  }
  return null;
}

export const dataService = {
  async getHeaderInfo() {
    const live = await fetchLiveTodayJson();
    if (live) {
      return {
        user: live.user,
        meta: {
          ...live.briefMeta,
          lastUpdated: live.briefMeta.time
        }
      };
    }
    return {
      user: mockData.user,
      meta: {
        ...mockData.briefMeta,
        lastUpdated: new Date().toLocaleTimeString('zh-TW', { hour: '2-digit', minute: '2-digit' })
      }
    };
  },

  async getWeather() {
    const live = await fetchLiveTodayJson();
    return live ? live.weather : mockData.weather;
  },

  async getHoroscope() {
    const live = await fetchLiveTodayJson();
    return live ? live.horoscope : mockData.horoscope;
  },

  async getExchangeRate() {
    const live = await fetchLiveTodayJson();
    return live ? live.exchangeRate : mockData.exchangeRate;
  },

  async getDrivingQuiz() {
    const live = await fetchLiveTodayJson();
    return live ? live.drivingQuiz : mockData.drivingQuiz;
  },

  async getAiNews() {
    const live = await fetchLiveTodayJson();
    return live ? live.aiNews : mockData.aiNews;
  },

  async getDailyAdvice() {
    const live = await fetchLiveTodayJson();
    return live ? live.dailyAdvice : mockData.dailyAdvice;
  },

  async refreshAll() {
    liveDataCache = null; // Clear cache
    const live = await fetchLiveTodayJson();
    return {
      weather: live ? live.weather : mockData.weather,
      horoscope: live ? live.horoscope : mockData.horoscope,
      exchangeRate: live ? live.exchangeRate : mockData.exchangeRate,
      drivingQuiz: live ? live.drivingQuiz : mockData.drivingQuiz,
      aiNews: live ? live.aiNews : mockData.aiNews,
      dailyAdvice: live ? live.dailyAdvice : mockData.dailyAdvice
    };
  }
};
